CREATE TABLE users (
    username VARCHAR(15) PRIMARY KEY,
    password VARCHAR(30) NOT NULL
);

CREATE TABLE heartbeats (
    username VARCHAR(15) PRIMARY KEY,
    last_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contacts (
    id SERIAL PRIMARY KEY,
    user1 VARCHAR(15) REFERENCES users(username) ON DELETE CASCADE,
    user2 VARCHAR(15) REFERENCES users(username) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);